### ISSUE TITLE
Manter as exchanges e moedas carregadas na memória?

### ISSUE THREAD

**Issue by naurojunior** [andreihod/cryptofolio#2]
@andreihod Devemos carregar uma vez só pro usuário as moedas / exchanges, manter na memória e deixar assim, ou toda vez que o usuário trocar de moeda ele recarrega as exchanges compatíveis?

**Comment by andreihod** [comment]
![Você Decide](https://i.ytimg.com/vi/MUW7KtGmvE8/hqdefault.jpg)

**Comment by naurojunior** [comment]
Vai ficar pra 2.0 então
